apiVersion: "v1"
kind: "Template"
metadata:
  name: nagios-template
objects:
  -
    apiVersion: "v1"
    kind: "Service"
    metadata:
      name: "nagios"
    spec:
      selector:
        provider: "rhmap"
        component: "nagios"
      ports:
        -
          protocol: "TCP"
          port: 8080
          targetPort: 8080
  -
    apiVersion: "v1"
    kind: "Route"
    metadata:
      name: "nagios"
    spec:
      host: "${NAGIOS_HOST}"
      to:
        kind: "Service"
        name: "nagios"
      tls:
        termination: "edge"
        insecureEdgeTerminationPolicy: "Allow"
  -
    apiVersion: "v1"
    kind: "PersistentVolumeClaim"
    metadata:
      name: "nagios-claim-1"
    spec:
      accessModes:
      - "ReadWriteOnce"
      resources:
        requests:
          storage: "1Gi"
  -
    apiVersion: "v1"
    kind: "DeploymentConfig"
    metadata:
      labels:
        provider: "rhmap"
        component: "nagios"
      name: "nagios"
    spec:
      replicas: 1
      selector:
        provider: "rhmap"
        component: "nagios"
      triggers:
      - type: ConfigChange
      strategy:
        resources: {}
        rollingParams:
          intervalSeconds: 1
          timeoutSeconds: 600
          updatePeriodSeconds: 1
        type: Recreate
      template:
        metadata:
          labels:
            provider: "rhmap"
            component: "nagios"
        spec:
          containers:
          - name: "nagios"
            image: "${NAGIOS_IMAGE_NAME}:${NAGIOS_IMAGE_VERSION}"
            ports:
              - containerPort: 8080
            env:
            - name: "SMTP_SERVER"
              value: "${SMTP_SERVER}"
            - name: "SMTP_USERNAME"
              value: "${SMTP_USERNAME}"
            - name: "SMTP_PASSWORD"
              value: "${SMTP_PASSWORD}"
            - name: "SMTP_TLS"
              value: "${SMTP_TLS}"
            - name: "SMTP_FROM_ADDRESS"
              value: "${SMTP_FROM_ADDRESS}"
            - name: "MBAAS_ADMIN_EMAIL"
              value: "${MBAAS_ADMIN_EMAIL}"
            - name: "NAGIOS_USER"
              value: "${NAGIOS_USER}"
            - name: "NAGIOS_PASSWORD"
              value: "${NAGIOS_PASSWORD}"
            - name: "MBAAS_ROUTER_DNS"
              value: "${MBAAS_ROUTER_DNS}"
            volumeMounts:
              - mountPath: "/var/log/nagios"
                name: "nagios-data-volume"
          volumes:
          - name: "nagios-data-volume"
            persistentVolumeClaim:
              claimName: "nagios-claim-1"
parameters:
-
  description: "Nagios hostname to expose a route as"
  name: NAGIOS_HOST
  required: true
-
  description: "SMTP server address to use for sending alert emails e.g. 1.2.3.4:25"
  name: "SMTP_SERVER"
  value: "localhost"
-
  description: "SMTP username"
  name: "SMTP_USERNAME"
  required: true
-
  description: "SMTP password"
  name: "SMTP_PASSWORD"
  required: true
-
  description: "Use TLS for message delivery (auto|yes|no)"
  name: "SMTP_TLS"
  value: "auto"
-
  description: "From email address for alerts"
  name: "SMTP_FROM_ADDRESS"
  value: "admin@example.com"
-
  description: "To email address for alerts"
  name: "MBAAS_ADMIN_EMAIL"
  value: "root@localhost"
-
  description: "Nagios admin username"
  name: "NAGIOS_USER"
  value: "nagiosadmin"
-
  description: "Nagios admin user password"
  name: "NAGIOS_PASSWORD"
  generate: "expression"
  from: "[a-zA-Z0-9]{10}"
-
  description: "Host or Service name for the MBaaS"
  name: "MBAAS_ROUTER_DNS"
  value: "fh-mbaas-service"
-
  description: "The name of the Nagios Docker image"
  name: "NAGIOS_IMAGE_NAME"
  value: "docker.io/rhmap/nagios"
-
  description: "The version of the Nagios Docker image"
  name: "NAGIOS_IMAGE_VERSION"
  value: "4.0.8-2"
